### ISSUE TITLE
Clear input control must be focusable and keyboard operable

### ISSUE THREAD

**Issue by levimcg** [maurercw/rivet-clearable-input#6]
@maurercw Thanks for working on this. I think you're off to a good start here.

The control you're using to trigger the clearing of the input is not accessible by keyboard right now. It looks like you're using some code on [this line](https://github.com/maurercw/rivet-clearable-input/blob/master/src/js/rivet-clearable-input.js#L47) to detect when the user is hovering over the background image (X) and attaching your event listener to the input. 

A better approach might be to use an actual `<button>` element for the control used to clear the input. The button could be hidden by default and then once a certain interaction happens it is made visible e.g. after the user type more that two characters: for example:

```javascript
if (input.value.length > 2) {
  // Show clear button with X icon
}
```

`<button>`s are prefect for this kind of control. When you use them you get all of the keyboard interaction for free and they're super easy to style. In this case removing the background color and including an svg inside the button for your icon. We have a "circle close" button that would be perfect for this:

https://github.com/indiana-university/rivet-icons/blob/develop/src/svg/rvt-icon-close-circle.svg

**Comment by maurercw** [comment]
@levimcg  How would I use the icon?  I don't see a published npm package for the icons anywhere.

**Comment by levimcg** [comment]
That’s a good point. Currently there is no officially published package on npm, but if your workflow absolutely relies on using the icons via an npm package you can install the icons directly from the GitHub repo using npm. The npm docs outline multiple options for how to do this:

https://docs.npmjs.com/cli/install.html

you could also download the repo which includes .svg source files you can use inline in the markup for your clearance control. 

Alternatively, you could also copy this svg markup from the source here:

https://github.com/indiana-university/rivet-icons/blob/develop/src/svg/rvt-icon-close-

Generally speaking inlining svg is the most reliable and performance-conscious way to use icons and how we’ve historically tried to use them in rivet.
